### PR TITLE
Removing config file in favor of config.in for nginx builds.

### PR DESCRIPTION
**Pull request by pareshverma91**
These files seems to have been deleted from codebase a while ago. Getting
rid of references to resolve build issues.

### CODE REVIEW

**Comment by allanbomsft** [comment]
Vladimir and I think this file is supposed to get generated on each build, based on config.in. Could you instead just delete this file and add it to gitignore? Would it resolve the problem?

**Review by vkrivopalov — APPROVED** [review]
Please either drop your old commit or squash it to the newer one before merging. Otherwise looks good.

**Review by allanbomsft — APPROVED** [review]

**Comment by pareshverma91** [comment]
It seems I don't have permissions to merge this. Could one of you please do that.

**Comment by allanbomsft** [comment]
Travis build is failing. Could you investigate why? Maybe just try to do a commit where you change something random and then another one to where you change it back, and then push to your github fork, in order to trigger the travis build again.

**Comment by vkrivopalov** [comment]
I think the Travis build failure happens because @pareshverma91 is using a branch in his own fork of the ModSecurity repo and it does not work well with our CI/CD. 
Unfortunately, today the branch needs to be pushed to microsoft/ModSecurity to build fine with Travis.

**Comment by vkrivopalov** [comment]
Has been merged as #118 - closing this one.

**Pull request closed without merging**
